package confluentUtils;

public enum MaritalStatus {
	UNKNOWN, SINGLE,MARRIED_CIVIL_PARTNER,WIDOWED,DIVORCED,LEGALLY_SEPERATED,COMMON_LAW,OTHER,NO_RESPONSE,
	DIVORCED_SEPERATED,OTHER_CBS,ENGAGED,SEPERATED;

}
